CREATE TABLE tb_state (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tb_city (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    state_id BIGINT NOT NULL,

    FOREIGN KEY (state_id) REFERENCES tb_state (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
